FROM apache/airflow:2.9.3-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*
USER airflow

COPY requirements/airflow.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --timeout=300 --retries=5 -r /tmp/requirements.txt
